### ISSUE TITLE
Some rows did not sync

### ISSUE THREAD

**Issue by killmondaymanagement** [GCalToolkit/Sheets2GCal#11]
Hey there its me again. 
I did a clean install, but it says unknown error for some random rows

![image](https://user-images.githubusercontent.com/98119326/150635937-e37c8010-69de-485c-b5b1-e41063ea8b0e.png)

**Comment by GCalToolkit** [comment]
You seem to have some end dates which are earlier than the start dates on the same day:

![IMG_20220122_123925](https://user-images.githubusercontent.com/23053190/150637056-d3fd71be-f4f0-4e90-88e3-b12bd27ba085.jpg)
