### ISSUE TITLE
Script error... maybe

### ISSUE THREAD

**Issue by Zed7TS** [GCalToolkit/Sheets2GCal#14]
Hi,
everytime I update this pops up: 
ScriptError: Exception: Request failed for https://content-sheets.googleapis.com returned code 400. Truncated server response: { "error": { "code": 400, "message": "Range (S2GCal!A10997:H10997) exceeds grid limits. Max rows: 10996, max columns: 26", "status": ... (use muteHttpExceptions option to examine full response)

It looks like it's working anyway.
Anyone knows what it could be causing this?

**Comment by GCalToolkit** [comment]
Update - can you try again? I think I've fixed the problem and Sheets2GCal should now work as expected.

**Comment by Zed7TS** [comment]
works fine now! Thank you!
