### ISSUE TITLE
Wrong timezone when I create an event in Google Sheet

### ISSUE THREAD

**Issue by Ebourb** [GCalToolkit/Sheets2GCal#2]
Hi !
  
      This was working a couple hours ago, and now, when I create an event, let's say from 9am - 5pm (in the America/Toronto time zone), when I sync the Google Sheet with Google Calendar, the calendar displays it from 3am - 11am.  The calendar is in (GMT-04:00) Eastern time - Toronto.  
![Error example 01](https://user-images.githubusercontent.com/82479179/114631043-ddc41580-9c89-11eb-80c5-7fab3ff42b9c.jpg)

**Comment by GCalToolkit** [comment]
Hi, can you please reload and test again now? I implemented a fix for a DST
issue which seems to have broken other things... It's been reverted so
things should now be as they were. Sorry for the inconvenience!

**Comment by Ebourb** [comment]
Fixed ! Thank you very much for the fast response, very much appreciated !
