### ISSUE TITLE
It is updated 1 day ago

### ISSUE THREAD

**Issue by DarioMontecino** [GCalToolkit/Sheets2GCal#3]
From the google spreadsheet I enter the date and time that I want to synchronize. Clicking on "update" is sent to the google calendar, but it shits a day behind. For example, I load the date 19 / April / 2021 in the google spreadsheet, but the date 18 / April / 2021 is loaded in the calendar.

**Comment by GCalToolkit** [comment]
Hi Dario, are you sure that your Sheet and Google Calendar are using the same timezone setting? If so, does this happen for all-day events, timed events, or both? And does it happen for single events, repeat events, or both?

**Comment by DarioMontecino** [comment]
I have the spreadsheet and calendar with the same -3 GMT time zone. The events that I charge are only one day long, all with a start time and an end time.
For example, it starts April 19, 10:00 a.m. and ends April 19, 8:00 p.m.
The time is loaded correctly, but the day is loaded with date April 18 at 10:00 a.m. to 8:00 p.m.

**Comment by GCalToolkit** [comment]
Thanks for that information - I've found the cause and updated accordingly, but it may take a short while (usually only minutes) for you to get the latest version, and you may have to reload the page. Please let me know if this fixes it - and/or if it creates any new issues!
