### ISSUE TITLE
event COLOR when REPEAT column is set to weekly

### ISSUE THREAD

**Issue by tes36** [GCalToolkit/Sheets2GCal#33]
When the cells in the REPEAT column are set to weekly, it doesn't matter what color you put in Color as it always shows the default color.

(In the cells, for example, it says BASIL but in Google Calendar it shows the default color.)

**Comment by GCalToolkit** [comment]
To reproduce this do I just need to create a repeat event with a specific colour? Or first create an event then change it to a repeat? And thank you for your feedback!

**Comment by tes36** [comment]
I've test it with different colours (colours are added as copy paste as "only values", maybe is this because cell color either change).

It's already set to weekly when is created

**Comment by GCalToolkit** [comment]
This should now be fixed now but the update might take a short while to roll out. Thank you for pointing it out and please let me know if it still doesn't work as expected by later today.

**Comment by tes36** [comment]
it's working now, thank you for fixing it so quickly
