### ISSUE TITLE
start and end time set to all-day after updating the event

### ISSUE THREAD

**Issue by tes36** [GCalToolkit/Sheets2GCal#34]
When I create a new event with the “start time” and “end time” cells having values, the event is created with a start time and end time, it works fine.

If after that, I update the event, it becomes an all-day event.

But in the cells, it shows the start and end time, it is displayed as an all-day event in the calendar (with the all-day event checkbox set to true).

**Comment by GCalToolkit** [comment]
Are you saying that the event changes from a timed event to an all-day event in Google Calendar when you edit something else in the event using Sheets2GCal, even though you didn't remove the Start/End times?

**Comment by tes36** [comment]
exactly that, on Sheets2GCal sheet it still appears START and END time but if I go to the calendar, it appears checked as an ALL-DAY event

**Comment by GCalToolkit** [comment]
If you only edit the Start and/or End times and update Google calendar from the Sheet does that work correctly? It sounds as though Sheets2GCal can't read the Start or End times when updating the event - are you sure that the Column header names haven't been changed?

**Comment by tes36** [comment]
![image](https://github.com/GCalToolkit/Sheets2GCal/assets/123871375/723df668-2333-4d45-b815-d4293c42db8c)
I think it's ok. Maybe date or time format?

**Comment by tes36** [comment]
They haven't been changed

**Comment by GCalToolkit** [comment]
Thanks, I'll be testing this and your other issue this evening and will post back as soon as I have news.

**Comment by GCalToolkit** [comment]
I can't reproduce this problem - what are your settings for the Sheet's "locale"  (in the Sheet Settings  > General > Locale)? Also what is the Hour/Minute separator (usually a colon e.g 13:20) and  when you double-click a "Start Time"does the separator change?

**Comment by tes36** [comment]
Regional configuration is set to Spain, I've tried 13:20 and also 13:20:00 

I can't reproduce it now. Also weekly events that were transformed to ALL DAY are actually set to TIMED events, so it seems to be a temporary bug.

**Comment by GCalToolkit** [comment]
Ok, I have no idea how that could have caused that but please let me know if it happens again!
