### ISSUE TITLE
Unique events being merged - given same link

### ISSUE THREAD

**Issue by nzcoops** [GCalToolkit/Sheets2GCal#63]
![Screenshot 2024-08-27 at 9 05 39 PM](https://github.com/user-attachments/assets/3863368b-845f-47e8-b63d-9280d132240f)

I have a series of events, all data is in the cells, not formula based. 

When I sync, they are all given the same link and only one (the last in this particular string) actually shows in the calendar.
Have been using this for quite a few years without issue.

**Comment by GCalToolkit** [comment]
If the links are identical this means that the data in the "event ID" column (which is hidden by default) must have somehow been edited to the same value for all these rows - so each row is now linked to a single event in the calendar. When updating, the same event will be modified multiple times by each row... and when finished it'll correspond to the last row.

If the events are all still in the calendar you could set up a new Sheet and import to start afresh.

If that's not an option (if you have other data/columns in the sheet for example) then I suggest you first back up the calendar (export to iCal in Google Calendar Settings), then check the previous versions of the Sheet (File Menu > Previous Revisions) to find the most recent version that has different "event ID" values for each row, and if necessary restore that version, or just copy the "event ID" column data and paste it into the current Sheet version to replace the incorrect event IDs.

If you restore an earlier version you might also want to make a backup copy of the current version before doing this, in case you need to restore any data from it.

Please contact me by email if you have any doubts about how to fix this.

**Comment by GCalToolkit** [comment]
I should have added that if you simply need to create events from all the other rows you can just delete the data in the Event ID column for each event that you want to create, then Export the Sheet making sure the "Update" checkbox is checked for each row that you want to create an event.

**Comment by nzcoops** [comment]
Ah, this will be exactly it!

I didn't even spot the hidden columns along the top and when I copied the location down I must have also grabbed that ID. I ended up trialing a clean paste of just the first few columns into a new sheet and calendar, which all worked fine. So then I went back to my original, removed all content, and then just pasted the event name/date/time etc - obviously not copy/pasting the hidden Event ID (dumb luck at the time rather than intention) and it came right.

Good to know what was actually behind it though - thanks!

**Comment by GCalToolkit** [comment]
Glad you got it sorted and thanks for letting me know! I wasn't sure whether to hide the Event ID column by default, but decided that it was probably better that way for simplicity... I'll add some information about that in the help so people who copy rows know to look out for that.
