### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by killmondaymanagement** [GCalToolkit/Sheets2GCal#9]
Hey

first of all thanks for this stuff
my only problem is it's creating a new entry instead of updating the existing one

Is this a bug or am i doing something wrong?

Thanks in advance
Andrew

**Comment by GCalToolkit** [comment]
Hi Andrew, if you unhide the "EventID" column can you see any event ID for three event you are editing? And does the link provided open the correct event?

**Comment by killmondaymanagement** [comment]
Hi! As I see it does not register EventID except the first row.

**Comment by killmondaymanagement** [comment]
And also it say data validation error in A column *number* which Im trying to update

**Comment by GCalToolkit** [comment]
Ok, best to fix that error first then... Column A should only contain the "Delete" checkboxes though, or did you move columns around?

**Comment by killmondaymanagement** [comment]
Ah now I see I accidentally removed the ID and Link columns... I did a clean restart and now it works fine! thanks for your hyperspeed support!

**Comment by GCalToolkit** [comment]
Glad to hear that's sorted :) You can actually move columns around, except for Delete and Update, but if you delete other columns, bad things will happen!
